name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    strategy:
      matrix:
        kaitai-version:
          - '0.10'
          - '0.9'
          - '0.8'
          - '0.7'
          - '0.6'
          - '0.5'
          - '0.4'
          - '0.3'
          - '0.2'

    name: Build and publish Docker image (v${{ matrix.kaitai-version }})

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          # TODO: Turn this on once the CI is confirmed to work
          push: false
          load: true
          tags: jonahsnider/kaitai-struct-compiler:${{ matrix.kaitai-version }}
          file: ./${{ matrix.kaitai-version }}.Dockerfile
